baseURL = "http://barbarasmidrkalova.cz"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Barbara Šmidrkalová"
[menu]
sitemap = []
[[menu.main]]
name = "Kontakt"
url = "#contact"
weight = 2
[[menu.main]]
name = "Služby"
url = "#service"
weight = 1
[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "© Barbara Šmidrkalová"
footerLogo = "images/site-navigation/logo-b.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/untitled-design-1.png"
[params.address]
addressLine1 = ""
addressLine2 = "Litoměřice"
email = "barbara.smidrkalova@gmail.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+420 605 161 153"
[params.footerJumbo]
bigTitle = "Pomohu vám mít uvolněné ruce i mysl..."
button = "Kontaktujte mě..."
smallTitle = "Všeho s mírou"
[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"
[[params.social]]
icon = "fa-linkedin-square"
url = "https://cz.linkedin.com/in/%C5%A1midrkalov%C3%A1-barbara"
weight = 2
[[params.social-false]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social-false]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social-false]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
